name: GitHub Stats Update
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual trigger
    
jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_COMMIT }}
          
      - name: Generate Stats
        uses: VatsalSy/commits-readme-stats@v2.0.0
        with:
          GH_COMMIT: ${{ secrets.GH_COMMIT }}
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          COMMIT_MESSAGE: 'docs(stats): update github stats'
